// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppMounted() {
  return window['go']['controller']['Controller']['AppMounted']();
}

export function GetApplicationConfig() {
  return window['go']['controller']['Controller']['GetApplicationConfig']();
}

export function GetAssetMeta(arg1) {
  return window['go']['controller']['Controller']['GetAssetMeta'](arg1);
}

export function GetLastState() {
  return window['go']['controller']['Controller']['GetLastState']();
}

export function IsAppMounted() {
  return window['go']['controller']['Controller']['IsAppMounted']();
}

export function LLMAsk(arg1) {
  return window['go']['controller']['Controller']['LLMAsk'](arg1);
}

export function LLMInterrupt() {
  return window['go']['controller']['Controller']['LLMInterrupt']();
}

export function LLMWait() {
  return window['go']['controller']['Controller']['LLMWait']();
}

export function Log(arg1, arg2) {
  return window['go']['controller']['Controller']['Log'](arg1, arg2);
}

export function OpenFileDialog(arg1) {
  return window['go']['controller']['Controller']['OpenFileDialog'](arg1);
}

export function Restart(arg1) {
  return window['go']['controller']['Controller']['Restart'](arg1);
}

export function Shutdown() {
  return window['go']['controller']['Controller']['Shutdown']();
}

export function TriggerRestart() {
  return window['go']['controller']['Controller']['TriggerRestart']();
}
