// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {controller} from '../models';
import {history} from '../models';
import {tools} from '../models';

export function AppMounted():Promise<void>;

export function GetApplicationConfig():Promise<model.Config>;

export function GetAssetMeta(arg1:string):Promise<controller.AssetMeta>;

export function GetAvailableProfiles():Promise<Record<string, model.Profile>>;

export function GetCurrentConversation():Promise<controller.LLMMessages>;

export function GetLastState():Promise<string>;

export function HistoryGetCount():Promise<number>;

export function HistoryGetLast(arg1:number,arg2:number):Promise<Array<history.Entry>>;

export function HistorySearch(arg1:string):Promise<Array<history.Entry>>;

export function IsAppMounted():Promise<boolean>;

export function LLMApproveToolCall(arg1:string):Promise<void>;

export function LLMAsk(arg1:controller.LLMAskArgs):Promise<string>;

export function LLMInterrupt():Promise<void>;

export function LLMRejectToolCall(arg1:string):Promise<void>;

export function LLMWait():Promise<string>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function OpenFileDialog(arg1:controller.OpenFileDialogArgs):Promise<Array<string>>;

export function Restart(arg1:string):Promise<void>;

export function SetActiveProfile(arg1:string):Promise<model.Config>;

export function SetBuiltinTools(arg1:tools.BuiltIns):Promise<void>;

export function Shutdown():Promise<void>;

export function TriggerRestart():Promise<void>;
