// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppMounted() {
  return window['go']['controller']['Controller']['AppMounted']();
}

export function GetInitialPrompt() {
  return window['go']['controller']['Controller']['GetInitialPrompt']();
}

export function LLMAsk(arg1) {
  return window['go']['controller']['Controller']['LLMAsk'](arg1);
}

export function LLMInterrupt() {
  return window['go']['controller']['Controller']['LLMInterrupt']();
}
