// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function AppMounted():Promise<void>;

export function GetInitialPrompt():Promise<string>;

export function LLMAsk(arg1:controller.LLMAskArgs):Promise<string>;

export function LLMInterrupt():Promise<void>;
