// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {model} from '../models';
import {history} from '../models';
import {tools} from '../models';
import {mcp} from '../models';

export function AppMounted():Promise<void>;

export function GetApplicationConfig():Promise<controller.ApplicationConfig>;

export function GetAssetMeta(arg1:string):Promise<controller.AssetMeta>;

export function GetAvailableProfiles():Promise<Record<string, model.ProfileMeta>>;

export function GetCurrentConversation():Promise<controller.LLMMessages>;

export function GetDebugConfig():Promise<model.DebugConfig>;

export function GetLastState():Promise<string>;

export function HistoryGetCount():Promise<number>;

export function HistoryGetLast(arg1:number,arg2:number):Promise<Array<history.Entry>>;

export function HistorySearch(arg1:string):Promise<Array<history.Entry>>;

export function IsAppMounted():Promise<boolean>;

export function LLMApproveToolCall(arg1:string):Promise<void>;

export function LLMAsk(arg1:controller.LLMAskArgs):Promise<string>;

export function LLMInterrupt():Promise<void>;

export function LLMRejectToolCall(arg1:string):Promise<void>;

export function LLMWait():Promise<string>;

export function ListMcpCommandTools():Promise<Array<any>>;

export function ListMcpHttpTools():Promise<Array<any>>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function OpenFileDialog(arg1:controller.OpenFileDialogArgs):Promise<Array<string>>;

export function Restart(arg1:string):Promise<void>;

export function SetActiveProfile(arg1:string):Promise<model.Profile>;

export function SetBuiltinTools(arg1:tools.BuiltIns):Promise<void>;

export function SetMcpTools(arg1:mcp.Config):Promise<void>;

export function Shutdown():Promise<void>;

export function TriggerRestart():Promise<void>;
